Repository Laravel-Backpack/BackupManager, pull requests merged in 2022-03, with the labels that each got.

#87 update backup.php
  src/resources/lang/en/backup.php
  src/resources/lang/es/backup.php
  src/resources/lang/fr/backup.php
  src/resources/lang/pt/backup.php
  src/resources/lang/pt_br/backup.php
  src/resources/views/backup.blade.php
Labels: Priority: SHOULD

#102 [New version] Moving configs to separate backupmanager file, remove old dependencies
  README.md
  composer.json
  src/BackupManagerServiceProvider.php
  src/app/Http/Controllers/BackupController.php
  src/config/backup.php
  src/config/backupmanager.php
  src/resources/lang/en/backup.php
  src/resources/lang/pt/backup.php
  src/resources/views/backup.blade.php
Labels: bug, Priority: SHOULD

#104 removed v3 config file in order to work with any version of spatie/laravel-backup
  README.md
  src/BackupManagerServiceProvider.php
  src/config/backup.php
Labels: Priority: MUST
